version: 0.2

env:
  variables:
    ECR_REGISTRY_URL: '819988951863.dkr.ecr.us-east-1.amazonaws.com/monte-piedad'
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REGISTRY_URL:latest .
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG="build-$COMMIT_HASH"
      - docker tag $ECR_REGISTRY_URL:latest $ECR_REGISTRY_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY_URL:latest
      - docker push $ECR_REGISTRY_URL:$IMAGE_TAG
      - echo Writing image definitions file...
      - ssss
      - printf '{"AWSEBDockerrunVersion":"1","Authentication":{"Bucket":"monte-piedad-configs","Key":".dockercfg"},"Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":9000,"HostPort":80}]}' $ECR_REGISTRY_URL:$IMAGE_TAG > Dockerrun.aws.json
      - cat Dockerrun.aws.json
artifacts:
  files: Dockerrun.aws.json
