# fly.toml app configuration file generated for monte-backend-dry-butterfly-2134 on 2024-01-09T22:56:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "monte-backend-dry-butterfly-2134"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/api/health"
    port = 9000
    timeout = "10s"
    type = "http"